// <auto-generated />
using CinemaApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CinemaApp.Migrations
{
    [DbContext(typeof(JobContext))]
    [Migration("20191201200848_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CinemaApp.Models.Genres", b =>
                {
                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Genre");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Genre = "Sci-Fi"
                        },
                        new
                        {
                            Genre = "Comedy"
                        },
                        new
                        {
                            Genre = "Sad"
                        });
                });

            modelBuilder.Entity("CinemaApp.Models.Movies", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Genre1")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Movie_Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Released")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.HasIndex("Genre1");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Movie_Genre = "Sci-Fi",
                            Name = "Harry Potter 1",
                            Released = 2019
                        },
                        new
                        {
                            MovieId = 2,
                            Movie_Genre = "Sci-Fi",
                            Name = "Harry Potter 2",
                            Released = 2018
                        },
                        new
                        {
                            MovieId = 3,
                            Movie_Genre = "Sci-Fi",
                            Name = "Harry Potter 3",
                            Released = 2017
                        },
                        new
                        {
                            MovieId = 4,
                            Movie_Genre = "Comedy",
                            Name = "Bruce Almighty",
                            Released = 2017
                        },
                        new
                        {
                            MovieId = 5,
                            Movie_Genre = "Sad",
                            Name = "Titanic",
                            Released = 2017
                        });
                });

            modelBuilder.Entity("CinemaApp.Models.Movies", b =>
                {
                    b.HasOne("CinemaApp.Models.Genres", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("Genre1");
                });
#pragma warning restore 612, 618
        }
    }
}
