// <auto-generated />
using CinemaApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CinemaApp.Migrations
{
    [DbContext(typeof(JobContext))]
    [Migration("20191206214348_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CinemaApp.Models.GenreMovieVM", b =>
                {
                    b.Property<string>("genreVM")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("movieIdVM")
                        .HasColumnType("int");

                    b.Property<string>("movies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("genreVM");

                    b.ToTable("GenreMovieVM");

                    b.HasData(
                        new
                        {
                            genreVM = "Sci-Fi",
                            movieIdVM = 123,
                            movies = "Harry Potter and the Philosopher's Stone, Harry Potter and the Chamber of Secrets, Harry Potter and the Prisoner of Azkaban"
                        },
                        new
                        {
                            genreVM = "Comedy",
                            movieIdVM = 45,
                            movies = "Bruce Almighty, Borat"
                        },
                        new
                        {
                            genreVM = "Sad",
                            movieIdVM = 67,
                            movies = "Titanic, Marley and Me"
                        });
                });

            modelBuilder.Entity("CinemaApp.Models.Genres", b =>
                {
                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("GenreMovieVMgenreVM")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Genre");

                    b.HasIndex("GenreMovieVMgenreVM");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Genre = "Sci-Fi"
                        },
                        new
                        {
                            Genre = "Comedy"
                        },
                        new
                        {
                            Genre = "Sad"
                        });
                });

            modelBuilder.Entity("CinemaApp.Models.Movies", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Genre1")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GenreMovieVMgenreVM")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Movie_Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Released")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.HasIndex("Genre1");

                    b.HasIndex("GenreMovieVMgenreVM");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Movie_Genre = "Sci-Fi",
                            Name = "Harry Potter and the Philosopher's Stone",
                            Released = 2001
                        },
                        new
                        {
                            MovieId = 2,
                            Movie_Genre = "Sci-Fi",
                            Name = "Harry Potter and the Chamber of Secrets",
                            Released = 2002
                        },
                        new
                        {
                            MovieId = 3,
                            Movie_Genre = "Sci-Fi",
                            Name = "Harry Potter and the Prisoner of Azkaban",
                            Released = 2004
                        },
                        new
                        {
                            MovieId = 4,
                            Movie_Genre = "Comedy",
                            Name = "Bruce Almighty",
                            Released = 2005
                        },
                        new
                        {
                            MovieId = 5,
                            Movie_Genre = "Comedy",
                            Name = "Borat",
                            Released = 2006
                        },
                        new
                        {
                            MovieId = 6,
                            Movie_Genre = "Sad",
                            Name = "Titanic",
                            Released = 2001
                        },
                        new
                        {
                            MovieId = 7,
                            Movie_Genre = "Sad",
                            Name = "Marley and Me",
                            Released = 2008
                        });
                });

            modelBuilder.Entity("CinemaApp.Models.Genres", b =>
                {
                    b.HasOne("CinemaApp.Models.GenreMovieVM", null)
                        .WithMany("GenresVM")
                        .HasForeignKey("GenreMovieVMgenreVM");
                });

            modelBuilder.Entity("CinemaApp.Models.Movies", b =>
                {
                    b.HasOne("CinemaApp.Models.Genres", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("Genre1");

                    b.HasOne("CinemaApp.Models.GenreMovieVM", null)
                        .WithMany("MoviesVM")
                        .HasForeignKey("GenreMovieVMgenreVM");
                });
#pragma warning restore 612, 618
        }
    }
}
